export default{
    woman:{
        xs:{
            minBoy:140,
            maxBoy:160,
            minGogus:65,
            maxGogus:86,
            minBel:55,
            maxBel:66,
            minKalca:85,
            maxKalca:94
        },
        s:{
            minBoy:161,
            maxBoy:167,
            minGogus:87,
            maxGogus:92,
            minBel:67,
            maxBel:72,
            minKalca:95,
            maxKalca:100
        },
        m:{
            minBoy:168,
            maxBoy:175,
            minGogus:93,
            maxGogus:98,
            minBel:73,
            maxBel:78,
            minKalca:101,
            maxKalca:106,
        },
        l:{
            minBoy:176,
            maxBoy:181,
            minGogus:99,
            maxGogus:104,
            minBel:79,
            maxBel:85,
            minKalca:107,
            maxKalca:112,
        },
        xl:{
            minBoy:182,
            maxBoy:190,
            minGogus:105,
            maxGogus:108,
            minBel:86,
            maxBel:90,
            minKalca:113,
            maxKalca:120,
        }
    },
    man:{
        xs:{
            minBoy:140,
            maxBoy:160,
            minGogus:75,
            maxGogus:95,
            minBel:74,
            maxBel:80,
            minKalca:85,
            maxKalca:92
        },
        s:{
            minBoy:161,
            maxBoy:167,
            minGogus:96,
            maxGogus:101,
            minBel:81,
            maxBel:84,
            minKalca:93,
            maxKalca:96
        },
        m:{
            minBoy:168,
            maxBoy:175,
            minGogus:102,
            maxGogus:107,
            minBel:85,
            maxBel:90,
            minKalca:97,
            maxKalca:100,
        },
        l:{
            minBoy:176,
            maxBoy:181,
            minGogus:108,
            maxGogus:113,
            minBel:91,
            maxBel:96,
            minKalca:101,
            maxKalca:104,
        },
        xl:{
            minBoy:182,
            maxBoy:198,
            minGogus:114,
            maxGogus:120,
            minBel:114,
            maxBel:120,
            minKalca:105,
            maxKalca:115,
        }
    }
    
    
}